name: Example Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: app_credentials

      uses: actions/checkout@v2

    - name: Use GitHub Token
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        echo "Using GitHub Token"
        # Example command using the token
        curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/manoj5176
