name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      run: |
        sudo apt-get update
        sudo apt-get install -y libffi-dev python3-dev python3-venv build-essential
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install setuptools

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install cython kivy buildozer

    - name: Install Android SDK and Tools
      run: |
        sudo apt-get install -y openjdk-11-jdk wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
        unzip commandlinetools-linux-7302050_latest.zip -d android-sdk
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=${HOME}/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Initialize Buildozer
      run: |
        source venv/bin/activate
        buildozer init || true

    - name: Build APK
      run: |
        source venv/bin/activate
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: bin/*.apk
