name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libffi-dev libssl-dev automake
          pip3 install --user --upgrade cython virtualenv buildozer
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          ndk-version: 23.1.7779620
          components: platform-tools, platforms;android-31, build-tools;31.0.0
      
      - name: Accept Licenses
        run: |
          yes | sdkmanager --licenses
      
      - name: Ensure AIDL is installed
        run: |
          sdkmanager --install "build-tools;31.0.0"
          sdkmanager --install "platform-tools"
          sdkmanager --install "platforms;android-31"
      
      - name: Build APK
        run: |
          buildozer -v android debug --log-level 2
