name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Add missing repositories and update package list
      run: |
        sudo add-apt-repository universe
        sudo add-apt-repository multiverse
        sudo add-apt-repository restricted
        sudo apt-get update
        sudo apt-get install -y libtinfo5

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
