name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        mkdir -p $HOME/sdk/cmdline-tools
        unzip -d $HOME/sdk/cmdline-tools commandlinetools-linux-6858069_latest.zip
        mkdir -p $HOME/sdk/cmdline-tools/latest
        mv $HOME/sdk/cmdline-tools/cmdline-tools/* $HOME/sdk/cmdline-tools/latest/
        export ANDROID_HOME=$HOME/sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
        sdkmanager "build-tools;30.0.3" "platforms;android-30" "cmdline-tools;latest"

    - name: Build with Buildozer
      run: |
        sudo pip install buildozer
        buildozer android debug
