name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libffi-dev libssl-dev automake
          pip3 install --user --upgrade cython virtualenv buildozer
      
      - name: Initialize Buildozer
        run: buildozer init
      
      - name: Build APK
        run: |
          buildozer -v android debug --log-level 2
